// Stub types for Convex generated server types
// These are generated by `npx convex dev` but we need stubs for build
export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;

export const query: any = undefined;
export const mutation: any = undefined;
export const action: any = undefined;
export const internalQuery: any = undefined;
export const internalMutation: any = undefined;
export const internalAction: any = undefined;
